name: Build and Test .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'  # Adjust to your version if needed

    - name: Restore dependencies
      run: dotnet restore FlightPoc.sln

    - name: Build
      run: dotnet build FlightPoc.sln --configuration Debug --no-restore

    - name: Run tests
      run: dotnet test FlightPoc.sln --configuration Debug --no-restore --verbosity normal
